### ISSUE TITLE
Slovenian translations for Achievements

### ISSUE THREAD

**Issue by IWasBilbo** [The-Phi/project-hospital-translations-web#1]
1. **Ah that's the spot** -- depending on the context, but in any case **"Ah, to je pravo mesto"** sounds better (Kraj has a geographical connotation). If used in a "that feels good" context, "Ah, to je dobro", would be the most natural.

2. Similarly, "more spots" would be "več mest".

3. "Oh, all the spots" is in the wrong grammatical case and again, I'd use "mesto", so: "Oh, vsa mesta" or if it means that something is placed in all the spots, "Oh, na vseh mestih" is the mpst natural way of saying it.

4. Very nice! Absolutely beautiful! -- Zelo lepo! Absolutno (or, even better "Nedvomno" (undoubtedly)) najlepše!

5. Place 100 decorations -- "okraskov" sounds weird, "okrasek" is most commonly used in context of holiday decorations and christmas tree ornaments. I'd use "Postavite 100 dekoracij".
Also, instead of using the 2nd person plural formal verb forms, I'd use singular informal verb forms in a game, it sounds more natural, in this case "Postavi 100 dekoracij".

6. Going up! -- as an achievement, I'd rather say "Gremo gor!"

7. Build the maximum amount of floors. -- "Zgradi največje _možno_ število nadstropij!"

8. Builder -- Gradbenik

9. The Great wall of hospital -- "Veliki bolnišnični zid" and don't capitalize any words except for the first one

10. Place 30 trashcans -- "Postavi 30 košev za smeti" (koš za smeti = trashcan!)

11. Place 10 prefabs -- what prefab? House? Item? https://en.pons.com/translate?q=prefab&l=ensl&in=&lf=sl

12. Build functional hospital with every department. -- "Zgradi delujočo bolnišnico z vsakim oddelkom" OR even better (more clearly implied that it has to be at least one of each) "... z vsakim od oddelkov"

13. You are hired -- "Zaposleni ste"

14. Hire your first employee. -- "Zaposli prvo osebo" (Give employment = zaposli)

15. Hire 20 employees -- "Zaposli 20 oseb"

16. I insure you -- insure or ensure? "Zavarujem vas" or "Zagotavljam vam".

17. Assign a chief doctor with ‘good boss’ perk. -- "Postavi višjega zdravnika z lastnostjo "dobri šef""

18. Senior doctor in da house! --" Višji zdravnik v bajti!" (an attempt to translate the slang)

19. Withdraw blood from 50 patients under your care. -- "Vzemi kri 50 bolnikov v tvoji oskrbi"

20. Have 30 patients under your care undergo X-ray examination. -- "Naj 30 bolnikov opravi rentgenski pregled"

21. Misdiagnose 20 patients under your care. -- "Postavi napačno diagnozo 20 bolnikom v tvoji oskrbi."

22. Doctor = doktor

23. Diagnose correctly 20 times under your care. -- "20-krat postavi pravilno diagnozo bolnikom v tvoji oskrbi"

24. Hello? Anybody? -- "Halo? Kdorkoli?"

25. Take over a patient from the clinic and have him wait for more than two game hours. -- "Prevzemi bolnika iz klinike in naj čaka 2 uri v igri"

26. Spend = "Zapravi"

27. Experience 10 patients collapse in the clinic. = "V kliniki se onesvesti 10 bolnikov"

28. alcoholic = alkoholik & perk = lastnost

29. Spremenite jezik igre vsaj 3-krat. (wrong grammatical case for jezik)

30. Dopolnite stopnjo 1. (wrong case again, repeated-- stopnja -> stopnjo) or even better, "Dopolnite 1. stopnjo."

31. Mejster == majster (but this is very informal, albeit a funny expression)

32. Hidden achievement = "Skriti dosežek"

33. Continue playing to unlock this achievement = "Igraj še naprej, da odkleneš ta dosežek."

**Comment by The-Phi** [comment]
Thanks a lot! You've done a wonderful work!
I've updated all this.
Concerning:

> Place 10 prefabs -- what prefab? House? Item? https://en.pons.com/translate?q=prefab&l=ensl&in=&lf=sl

It's a prefab: you put an all equipped room (with stool, desk etc inside). 
So it's not a house. Later I've found "montažna gradnja". Would it be correct?

I thank so much again!

**Comment by IWasBilbo** [comment]
Oh. Prefabs (in any meaning) are not common in Slovenia so our vocabulary doesn't have a clear expression for that... I think the least ambiguous translation would be "Opremljena soba" (furnished room). Montažna soba could work too, but the meaning is unclear to a Slovenian speaker.

**Comment by The-Phi** [comment]
Updated with "Opremljena soba", thanks!
