### ISSUE TITLE
Slovenian translations for Skills

### ISSUE THREAD

**Issue by Sky-si** [The-Phi/project-hospital-translations-web#2]
1.	General Surgery Department – Oddelek za splošno kirurgijo
2.	Critical care medicine gives the doctor access to specialized diagnostic methods used at ICU. - Medicina intenzivne nege daje zdravniku dostop do specializiranih diagnostičnih metod, ki se uporabljajo na oddelku intenzivne nege.
3.	Operative surgery - Operativna kirurgija
4.	Operative surgery allows the doctor to act as main surgeon at General Surgery department and affects how often surgeries will end up with complications. Operativna kirurgija zdravniku omogoča, da dela kot glavni kirurg na oddelku splošne kirurgije in vpliva na pogostost pojavov kirurških zapletov.
5.	IM surgery - IM kirurgija
6.	Internal medicine allows the doctor to act as main surgeon at Internal Medicine department and affects how often surgeries will end up with complications. – Interna medicina zdravniku omogoča, da dela kot glavni kirurg na oddelku interne medicine in vpliva na pogostost pojavov kirurških zapletov.
7.	Orthopaedy is used in specialized examinations and for prescribing treatments at Orthopaedy department and allows the doctor to assist at surgery. - Ortopedija se uporablja pri specializiranih pregledih in pri predpisovanju zdravljenja na oddelku ortopedije in omogoča zdravniku, da pomaga pri operaciji.
8.	Orthopaedic surgery allows the doctor to act as main surgeon at Orthopaedy department and affects how often surgeries will end up with complications. - Ortopedska kirurgija zdravniku omogoča, da dela kot glavni kirurg na ortopedskem oddelku in vpliva na pogostost pojavov kirurških zapletov.
9.	Cardio-surgery - Srčna kirurgija
10.	Cardio-surgery allows the doctor to act as main surgeon at Cardiology department and affects how often surgeries will end up with complications. 	- Srčna kirurgija zdravniku omogoča, da dela kot glavni kirurg na kardiološkem oddelku in vpliva na pogostost pojavov kirurških zapletov.
11.	Neuro-surgery allows the doctor to act as main surgeon at Neurology department and affects how often surgeries will end up with complications. 	Nevrokirurgija zdravniku omogoča, da dela kot glavni kirurg na oddelku za nevrologijo in vpliva na pogostost pojavov kirurških zapletov.
12.	Anesthesiology is required for the doctor to act as an anesthesiologist at surgery and gives extra survival chance to collapsed patients stabilized by this doctor. \nDecreases death probability in collapsed patients. \nDecreases post operative complications after surgery. - Anesteziologija je potrebna, da lahko zdravnik pri kirurškem posegu sodeluje kot anesteziolog. Če kolabiranega pacienta stabilizira ta zdravnik, to izboljša možnost za preživetje. \nZmanjša verjetnost smrti pri kolabiranih pacientih.\nZmanjša pooperativne zaplete.
13.	Medical surgery nurse represent important part of operative surgical teams. – Operacijska medicinska sestra je pomemben del kirurške ekipe.
14.	Clinical Nurse Specialist – Specializirana medicinska sestra
15.	Clinical Nurse Specialist is capable of revealing appearance of patient’s symptoms. – Specializirana medicinska sestra je sposobna razkriti pojav pacientovih simptomov.
16.	Biochemistry gives access to various STAT laboratory tests. - Biokemija omogoča dostop do različnih nujnih laboratorijskih preiskav.
17.	Advanced biochemistry increases effectiveness of laboratory tests. - Napredna biokemija izboljša učinkovitost laboratorijskih preiskav.
18.	Radiology specialist is capable of fully operating radiology imaging machines and other radiology related equipment. - Specialist radiologije je sposoben upravljati z napravami za slikovno diagnostiko in z ostalo radiološko opremo.
19.	GIT technologist is capable of operating examination devices related to General surgery. - Tehnik gastroenterologije je sposoben upravljati z diagnostičnimi napravami povezanimi s splošno kirurgijo.
20.	USG technologist is capable of operating Ultrasonographic devices. Ultrazvočni tehnik je sposoben upravljanja z ultrazvočnimi napravami.
21.	Cardiology technologist is capable of operating examination devices related to Cardiology. Kardiološki tehnik je sposoben upravljanja z diagnostičnimi napravami povezanimi s kardiologijo.
22.	Neurology technologist is capable of operating examination devices related to Neurology. - Nevrološki tehnik je sposoben upravljanja z diagnostičnimi napravami povezanimi z nevrologijo.
23.	Efficiency affects, how well janitors plan when cleaning different rooms. – Učinkovitost vpliva na to, kako dobro hišniki načrtujejo čiščenje različnih prostorov.
24.	Dexterity affects the speed when cleaning. - Spretnost vpliva na hitrost čiščenja.

These titles are a bit more difficult to translate properly so hopefully someone else is going to chip in:
1.	Intern - Zdravnik pripravnik
2.	Resident - Zdravnik sekundarij
3.	Attending - Sobni zdravnik
4.	Fellow	- Zdravnik specializant
5.	Specialist - Zdravnik specialist
6.	Nursing intern - Pripravnik zdravstvene nege
7.	Registered nurse - Medicinska sestra
8.	Nurse specialist - Specializirana medicinska sestra
9.	Junior scientist 	[Not sure what kind of scientists they mean here?]
10.	Senior scientist [?]
11.	Master scientist [?]
12.	Janitor - Hišnik
13.	Senior janitor [Not sure what to call this one.]
14.	Master janitor [Not sure about this one either.]

**Comment by The-Phi** [comment]
Thanks a lot for your interest! I'm moving the project to http://gilgagilga.pythonanywhere.com/ so this project website is deprecated. I think it will be better for anyone to contribute, check what has already been translated there.
