### ISSUE TITLE
Slovenian for BuldingMode

### ISSUE THREAD

**Issue by IWasBilbo** [The-Phi/project-hospital-translations-web#3]
Light tinted tiles: lightly colored, right? Which would be "Obarvane ploščice". Bleščeče means shiny.

Obarvane (ploščice) = light tinted (direct translation is colored, but the adjective implies that it's not fully colored; tinted)

Pobarvane (ploščice) = fully colored

Barvne (ploščice) = colored/of color

At 10&11 watch out for the correct order of words: Obarvane srednje ploščice & Pobarvane srednje ploščice (kind>size>noun, but 7&8 are correct as it is now)

14-17 Temna/svetla ploščica sounds better, you don't need "colored" in there, it's redundant

Laminate flooring -- Laminatna tla

Hardwood flooring -- Parket

Light/dark lino fl. -- Svetel/Temen linolej

Asphalt road variation -- in what context? "Sprememba..." means A change of the asphalt road, which is obviously wrong. If used with two textures or something, where you have 2 asphalt road types and this is the different one, I'd just use the assimilated word "Variacija asfaltne ceste"

Ambulance area -- ambulance = rešilni avto, or more commonly used, rešilec. So, the translation would be "Območje rešilnega avta (or -- rešilca)"

"Prodnik" is a single small rock... I would --although not really used like that-- differentiate between sand and gravel with "Mivka" (which is fine sand, like on a sandy beach or in a sandpit) and "Pesek" (to which, for me, the first association would be closer to gravel). The translation is not ideal, but 100% everyone knows what kind of fine sand "mivka" is and it would be implied that "pesek" is something other than fine sand, like the type of "sand" they put on roads in winter, which in English is closer to gravel. So, Sand - Mivka and Gravel-Pesek is best in my opinion. You can google these two just to be sure.

Ground--tla (same as floor)

Concrete tiled wall -- Stena iz betonskih plošč

Two colored stripes -- Dve obarvani črti (stripe = trak/črta, preferably the latter one)

Half-colored wall with stripe -- Napol pobarvana stena s črto

Bottom colored wall -- Stena, obarvana na dnu

Watch window -- Ogledno okno (very awkward translation) (?)

Sliding double door -- Dvojna drsna vrata

Double door = dvojna vrata (eg. at 108)

Staff requirements = Zahtevano osebje

Basic clinical office for simple examinations and treatments. Staff requirements:\n1x Doctor -- "Osnovna bolnišnična pisarna za preproste preglede in zdravljenja. Zahtevano osebje:\n1x Zdravnik"

The common room is the place for hospital staff to rest, study and eat. -- "Skupna soba je prostor za počitek, prehranjevanje in študij osebja."

The reception ensures that patients get triaged correctly upon arrival, so patients with high risk get prioritized during their visit.\n\nMin. Staff requirements: \n1x Nurse - Receptionist -- "Recepcija zagotovi, da so bolniki pravilno razvrščeni ob prihodu, tako da so tisti z visokim tveganjem prednostno obravnavani.\n\nMin. zahtevano osebje: \n1x Sestra - Receptor"

124-...

Use adjectives for lab kinds, not nouns (also, the prepositions would not be "na" but "za"). 
Med Lab = Medicinski laboratorij
Orthopaedic Lab = Ortopedski laboratorij
Cardiology Lab = Kardiološki laboratorij
Neurology Lab = Nevrološki laboratorij

Cleaning closet = Omara za čiščenje

Sonography unit -- Unit as in "team" or "machine/appliance"? If team, use "Ultrazvočna enota" (Kardiografska, Nevrološka...). If machine, just skip "unit" and use Ultrazvok, etc. (Nevermind, I think it's clear that it's meant as a team)

Trauma center -- Urgenca & collapsed = nezavestne (unconscious?) or "sesedle" but this one is awkward to use

On-call room -- Soba dežurnih 

Regular ward -- Redni oddelek

High dependency unit provides higher level of medical care for hospitalized patients. \n\nMin. Staff requirements: \n1x Doctor \n1x Nurse \n(Personnel based in On-call room and Nurses station) -- let's do it like this "HDU (High Dependency Unit) je enota z večjo ravnjo skrbi za bolnike".

184-185 : Just a typo in 185, copy the 184 translation in beginning

(I'm out of time for today, can't translate any more, be back soon)

**Comment by The-Phi** [comment]
I'm closing the issue since I will maintain the website at http://gilgagilga.pythonanywhere.com/ and all the comment/suggestions there as I've written.
